version: '2.8'

services:
  postgres:
    image: postgres:latest
    restart: always
    environment:
      POSTGRES_DB: nest-crud
      POSTGRES_USER: smoeury-songvat
      POSTGRES_PASSWORD: nest-sample5577
    ports:
      - '5432:5432'
    volumes:  
      - postgres_data:/var/lib/postgresql/data
volumes:
  postgres_data: